# Generated by Django 5.2.15 on 2026-08-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="prefix_name",
            field=models.CharField(
                choices=[("นาย", "นาย"), ("นางสาว", "นางสาว"), ("นาง", "นาง")],
                default="นาย",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="st_id",
            field=models.CharField(default="000000", max_length=20),
            preserve_default=False,
        ),
    ]
