# Generated by Django 5.2.15 on 2026-08-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_student_prefix_name_student_st_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mj_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "major",
                "verbose_name_plural": "majors",
            },
        ),
    ]
