# Generated by Django 5.2.15 on 2026-08-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app1.major"
            ),
        ),
    ]
