# Generated by Django 5.2.15 on 2026-08-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_student_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="st_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
